[param]
interface_type = "Uart"
comport_uart = "/dev/tty.usbmodem211201"
chip = "BL616/618"
chip_name = "bl616"
chip_type = "bl616"
speed_uart = "2000000"
speed_jlink = "1000"
erase = "1"
skip_mode = "0x0, 0x0"
boot2_isp_mode = "0"

[check_box]
efuse = false

[input_path]
efuse = ""
config = "/Users/nimish/Projects/bl616_tmpl/flash_prog_config.ini"

[FW]
addr = "0x000000"
path = "/Users/nimish/Projects/bl616_tmpl/./build/app/app.bin"
